### ISSUE TITLE
I dig it but I cannot see what I select

### ISSUE THREAD

**Issue by NdagiStanley** [BolajiOlajide/folabelle#1]
Yo! I really like the theme. There is one thing that you can rectify to make me use it.
### Expected behaviour
When I am going through options in a drop-down menu, the selected option should be a lighter or darker shade than the menu.
### Actual behaviour
When I am going through options in a drop-down menu, I cannot see what I have selected since there is no visual difference between the selected option and the menu.
### Steps to reproduce the behaviour

1. Have `folabelle` as the active theme
2. Open a workspace of choice
3. Select ⌘P to select a file in a workspace, that you want to open
4. Using the keyboard arrow keys, you cannot tell which option is active

<img width="815" alt="screenshot 2018-03-12 17 13 24" src="https://user-images.githubusercontent.com/15629602/37288581-b1a770fe-2618-11e8-958a-672f96b93850.png">

**Comment by BolajiOlajide** [comment]
Thanks @NdagiStanley. Looking into it.

**Comment by BolajiOlajide** [comment]
<img width="734" alt="screen shot 2018-03-13 at 02 12 39" src="https://user-images.githubusercontent.com/25608335/37317352-a3f5cbc6-2664-11e8-8a0b-024334a64a2d.png">

Resolved @NdagiStanley

**Comment by BolajiOlajide** [comment]
Kindly update the package on your PC and try again.

**Comment by NdagiStanley** [comment]
Thanks. Good job.
